import type { Promotion } from '../types';

export let mockPromotions: Promotion[] = [
  {
    id: 'p1',
    restaurantId: '1',
    title: 'Pizza em Dobro',
    condition: 'Peça 1 pizza e leve 2',
    days: ['ter', 'qua'],
    startTime: '18:00',
    endTime: '22:00',
    active: true,
  },
  {
    id: 'p2',
    restaurantId: '1',
    title: 'Happy Hour de Bebidas',
    condition: '30% OFF em todas as bebidas',
    days: ['sex', 'sab'],
    startTime: '17:00',
    endTime: '20:00',
    active: true,
  },
  {
    id: 'p3',
    restaurantId: '1a',
    title: 'Segunda do Hambúrguer',
    condition: 'Combo hambúrguer + batata + bebida com 25% OFF',
    days: ['seg'],
    startTime: '11:00',
    endTime: '23:00',
    active: true,
  },
  {
    id: 'p4',
    restaurantId: '1b',
    title: 'Quinta da Pizza',
    condition: 'Pizza grande com borda recheada no valor da média',
    days: ['qui'],
    startTime: '19:00',
    endTime: '22:00',
    active: true,
  },
  {
    id: 'p5',
    restaurantId: '2',
    title: 'Almoço Executivo',
    condition: 'Prato + bebida + sobremesa por R$ 29,90',
    days: ['seg', 'ter', 'qua', 'qui', 'sex'],
    startTime: '11:30',
    endTime: '14:30',
    active: true,
  },
];
