import type { Restaurant } from '../types/restaurant';

export const mockRestaurants: Restaurant[] = [
  {
    id: '1',
    slug: 'pizzaria-bella',
    name: 'Pizzaria Bella',
    logo: '🍕',
    plan: 'diamante',
    rating: 4.8,
    category: 'Italiana',
    distance: 1.2,
    isOpen: true,
    deliveryTime: '30-40 min',
    minOrder: 25,
    headerColor: '#C92924', // Vermelho padrão
  },
  {
    id: '2',
    slug: 'burger-house',
    name: 'Burger House',
    logo: '🍔',
    plan: 'ouro',
    rating: 4.6,
    category: 'Hamburgueria',
    distance: 0.8,
    isOpen: true,
    deliveryTime: '25-35 min',
    minOrder: 20,
  },
  {
    id: '3',
    slug: 'sushi-zen',
    name: 'Sushi Zen',
    logo: '🍣',
    plan: 'diamante',
    rating: 4.9,
    category: 'Japonesa',
    distance: 2.5,
    isOpen: true,
    deliveryTime: '40-50 min',
    minOrder: 35,
  },
  {
    id: '4',
    slug: 'taco-loco',
    name: 'Taco Loco',
    logo: '🌮',
    plan: 'prata',
    rating: 4.5,
    category: 'Mexicana',
    distance: 1.8,
    isOpen: true,
    deliveryTime: '30-40 min',
    minOrder: 22,
  },
  {
    id: '5',
    slug: 'salad-bar',
    name: 'Salad Bar',
    logo: '🥗',
    plan: 'ouro',
    rating: 4.7,
    category: 'Saudável',
    distance: 1.0,
    isOpen: false,
    deliveryTime: '20-30 min',
    minOrder: 18,
  },
  {
    id: '6',
    slug: 'churrascaria-gaucha',
    name: 'Churrascaria Gaúcha',
    logo: '🥩',
    plan: 'prata',
    rating: 4.4,
    category: 'Brasileira',
    distance: 3.2,
    isOpen: true,
    deliveryTime: '45-55 min',
    minOrder: 40,
  },
  {
    id: '7',
    slug: 'pasta-fresca',
    name: 'Pasta Fresca',
    logo: '🍝',
    plan: 'basico',
    rating: 4.3,
    category: 'Italiana',
    distance: 2.0,
    isOpen: true,
    deliveryTime: '35-45 min',
    minOrder: 28,
  },
  {
    id: '8',
    slug: 'acai-tropical',
    name: 'Açaí Tropical',
    logo: '🍨',
    plan: 'basico',
    rating: 4.6,
    category: 'Sobremesas',
    distance: 0.5,
    isOpen: true,
    deliveryTime: '15-25 min',
    minOrder: 15,
  },
  {
    id: '9',
    slug: 'padaria-do-bairro',
    name: 'Padaria do Bairro',
    logo: '🥖',
    plan: 'basico',
    rating: 4.2,
    category: 'Padaria',
    distance: 0.3,
    isOpen: true,
    deliveryTime: '10-20 min',
    minOrder: 10,
  },
  {
    id: '10',
    slug: 'temakeria-tokyo',
    name: 'Temakeria Tokyo',
    logo: '🍱',
    plan: 'ouro',
    rating: 4.8,
    category: 'Japonesa',
    distance: 1.5,
    isOpen: true,
    deliveryTime: '30-40 min',
    minOrder: 30,
  },
];
