import type { MenuCategory, MenuItem } from '../types/restaurant';

// Categorias por restaurante
export const mockCategories: MenuCategory[] = [
  // PIZZARIA BELLA (restaurantId: '1')
  { id: 'pb-destaques', name: '⭐ Destaques', order: 1, restaurantId: '1' },
  { id: 'pb-combos', name: '🎁 Combos', order: 2, restaurantId: '1' },
  { id: 'pb-classicas', name: '🍕 Pizzas Clássicas', order: 3, restaurantId: '1' },
  { id: 'pb-doces', name: '🍫 Pizzas Doces', order: 4, restaurantId: '1' },
  { id: 'pb-bebidas', name: '🥤 Bebidas', order: 5, restaurantId: '1' },
  { id: 'pb-sobremesas', name: '🍰 Sobremesas', order: 6, restaurantId: '1' },
  { id: 'pb-acompanhamentos', name: '🍟 Acompanhamentos', order: 7, restaurantId: '1' },
  
  // CATEGORIAS GENÉRICAS (para outros restaurantes)
  { id: 'bh-ofertas', name: '🎁 Ofertas', order: 1, restaurantId: '2' },
  { id: 'cat-1', name: 'Pizzas', order: 1 },
  { id: 'cat-2', name: 'Bebidas', order: 2 },
  { id: 'cat-3', name: 'Sobremesas', order: 3 },
  { id: 'cat-4', name: 'Pratos Brasileiros', order: 4 },
  { id: 'cat-5', name: 'Hambúrgueres e Lanches', order: 5 },
  { id: 'cat-6', name: 'Sushi e Temaki', order: 6 },
  { id: 'cat-7', name: 'Doces e Bolos', order: 7 },
  { id: 'cat-8', name: 'Saladas e Fit', order: 8 },
];

export const mockMenuItems: MenuItem[] = [
  // PIZZARIA BELLA - DESTAQUES
  {
    id: 'item-1',
    restaurantId: '1',
    name: 'Pizza Especial da Casa',
    description: 'Nossa criação exclusiva que combina ingredientes premium selecionados pelo chef. Uma experiência gastronômica única que só você encontra aqui.',
    ingredients: 'Molho especial da casa, mussarela de búfala, tomate seco, rúcula, parmesão e azeite trufado',
    image: '⭐',
    categoryId: 'pb-destaques',
    prices: {
      mymenu: 48.90,
      ifood: 52.90,
      ubereats: 51.90,
      rappi: 51.90,
    },
    exclusive: 'presencial',
    available: true,
    allergens: ['gluten', 'dairy'],
  },

  // PIZZARIA BELLA - COMBOS
  {
    id: 'item-2',
    restaurantId: '1',
    name: 'Combo Família (2 Pizzas + Bebida)',
    description: 'Duas pizzas à escolha acompanhadas de uma bebida 2L. Perfeito para famílias!',
    ingredients: 'Variado (escolher 2 pizzas) e refrigerante 2L',
    image: '🎁',
    categoryId: 'pb-combos',
    prices: {
      mymenu: 79.90,
      ifood: 89.90,
      ubereats: 85.90,
      rappi: 87.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-3',
    restaurantId: '1',
    name: 'Combo Casal (1 Pizza + Sobremesa + Bebida)',
    description: 'Uma pizza à escolha, um acompanhamento doce e uma bebida. Ideal para dois!',
    ingredients: 'Uma pizza à escolha, sobremesa e bebida 500ml',
    image: '🎁',
    categoryId: 'pb-combos',
    prices: {
      mymenu: 59.90,
      ifood: 67.90,
      ubereats: 64.90,
    },
    available: true,
    allergens: ['gluten', 'dairy', 'eggs'],
  },

  // PIZZARIA BELLA - PIZZAS CLÁSSICAS
  {
    id: 'item-4',
    restaurantId: '1',
    name: 'Pizza Margherita',
    description: 'A combinação atemporal de molho de tomate pelati, muçarela derretida e folhas frescas de manjericão, finalizada com um fio de azeite de oliva extra virgem.',
    ingredients: 'Molho de tomate, mussarela, manjericão e azeite',
    image: '🍕',
    categoryId: 'pb-classicas',
    prices: {
      mymenu: 35.90,
      ifood: 39.90,
      ubereats: 37.90,
      rappi: 38.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
    isOffer: true,
    offerPrice: 31.50,
  },
  {
    id: 'item-5',
    restaurantId: '1',
    name: 'Pizza Calabresa',
    description: 'Sabor marcante da calabresa artesanal com cebola roxa caramelizada sobre generosa camada de mussarela.',
    ingredients: 'Molho de tomate, mussarela, calabresa e cebola',
    image: '🍕',
    categoryId: 'pb-classicas',
    prices: {
      mymenu: 38.90,
      ifood: 42.90,
      ubereats: 40.90,
      rappi: 41.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-6',
    restaurantId: '1',
    name: 'Pizza Portuguesa',
    description: 'Uma explosão de sabores com presunto, ovos, cebola e azeitonas pretas sobre nossa massa artesanal.',
    ingredients: 'Molho de tomate, mussarela, presunto, ovos, cebola e azeitonas',
    image: '🍕',
    categoryId: 'pb-classicas',
    prices: {
      ifood: 45.90,
      ubereats: 43.90,
      rappi: 44.90,
      mymenu: 42.90,
    },
    available: true,
    allergens: ['gluten', 'dairy', 'eggs'],
  },
  {
    id: 'item-7',
    restaurantId: '1',
    name: 'Pizza Frango com Catupiry',
    description: 'Frango desfiado macio coberto com o famoso catupiry cremoso e mussarela derretida.',
    ingredients: 'Molho de tomate, mussarela, frango desfiado, catupiry e cebola',
    image: '🍕',
    categoryId: 'pb-classicas',
    prices: {
      mymenu: 40.90,
      ifood: 45.90,
      ubereats: 43.90,
      rappi: 44.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-8',
    restaurantId: '1',
    name: 'Pizza Quatro Queijos',
    description: 'Combinação de quatro queijos diferentes: mussarela, gorgonzola, parmesão e catupiry para um sabor inesquecível.',
    ingredients: 'Molho de tomate, mussarela, gorgonzola, parmesão, catupiry',
    image: '🍕',
    categoryId: 'pb-classicas',
    prices: {
      mymenu: 44.90,
      ifood: 49.90,
      ubereats: 47.90,
      rappi: 48.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },

  // PIZZARIA BELLA - PIZZAS DOCES
  {
    id: 'item-9',
    restaurantId: '1',
    name: 'Pizza Doce de Banana com Canela',
    description: 'Base crocante coberta com calda doce, banana fresca fatiada e polvilho de canela. Um sabor adocicado irresistível.',
    ingredients: 'Massa doce, banana, açúcar, canela e manteiga',
    image: '🍌',
    categoryId: 'pb-doces',
    prices: {
      mymenu: 28.90,
      ifood: 32.90,
      ubereats: 31.90,
      rappi: 31.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-10',
    restaurantId: '1',
    name: 'Pizza Doce de Chocolate com Morango',
    description: 'Pizza com cobertura de chocolate belga derretido, morangos frescos e um toque de calda de chocolate.',
    ingredients: 'Massa doce, chocolate belga, morango fresco, calda de chocolate e manteiga',
    image: '🍫',
    categoryId: 'pb-doces',
    prices: {
      mymenu: 32.90,
      ifood: 37.90,
      ubereats: 35.90,
      rappi: 36.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-11',
    restaurantId: '1',
    name: 'Pizza Doce de Goiabada com Queijo',
    description: 'Combinação clássica de goiabada cremosa com queijo meia cura derretido na massa crocante.',
    ingredients: 'Massa doce, goiabada, queijo meia cura e manteiga',
    image: '🍯',
    categoryId: 'pb-doces',
    prices: {
      mymenu: 26.90,
      ifood: 30.90,
      ubereats: 29.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },

  // PIZZARIA BELLA - BEBIDAS
  {
    id: 'item-12',
    restaurantId: '1',
    name: 'Refrigerante 2L',
    description: 'Bebida gelada perfeita para acompanhar sua refeição. Escolha entre Coca-Cola, Guaraná Antarctica ou Fanta Laranja.',
    ingredients: 'Refrigerante 2 litros - Coca-Cola, Guaraná ou Fanta',
    image: '🥤',
    categoryId: 'pb-bebidas',
    prices: {
      mymenu: 10.00,
      ifood: 12.00,
      ubereats: 11.00,
      rappi: 11.50,
    },
    available: true,
  },
  {
    id: 'item-13',
    restaurantId: '1',
    name: 'Suco Natural 500ml',
    description: 'Suco 100% natural feito na hora com frutas frescas selecionadas. Opções: laranja, limão ou morango.',
    ingredients: 'Frutas frescas (laranja, limão ou morango) e água',
    image: '🧃',
    categoryId: 'pb-bebidas',
    prices: {
      mymenu: 8.00,
      ifood: 9.50,
      ubereats: 9.00,
      rappi: 9.50,
    },
    available: true,
  },
  {
    id: 'item-14',
    restaurantId: '1',
    name: 'Água Mineral 500ml',
    description: 'Água mineral pura e refrescante. Disponível com ou sem gás, sempre gelada.',
    ingredients: 'Água mineral 500ml',
    image: '💧',
    categoryId: 'pb-bebidas',
    prices: {
      mymenu: 4.00,
      ifood: 5.00,
      ubereats: 4.50,
      rappi: 4.50,
    },
    available: true,
  },
  {
    id: 'item-15',
    restaurantId: '1',
    name: 'Cerveja Artesanal 600ml',
    description: 'Seleção de cervejas artesanais locais. Consulte opções disponíveis.',
    ingredients: 'Cerveja artesanal 600ml',
    image: '🍺',
    categoryId: 'pb-bebidas',
    prices: {
      mymenu: 14.90,
      ifood: 16.90,
      ubereats: 15.90,
    },
    available: true,
  },

  // PIZZARIA BELLA - SOBREMESAS
  {
    id: 'item-16',
    restaurantId: '1',
    name: 'Brownie de Chocolate',
    description: 'Brownie artesanal de chocolate belga, crocante por fora e cremoso por dentro, servido quente com sorvete de creme e calda de chocolate.',
    ingredients: 'Chocolate belga, farinha, ovos, manteiga, açúcar, nozes e sorvete de creme',
    image: '🍫',
    categoryId: 'pb-sobremesas',
    prices: {
      mymenu: 15.90,
      ifood: 17.90,
      ubereats: 16.90,
      rappi: 17.50,
    },
    available: true,
    allergens: ['gluten', 'dairy', 'eggs', 'nuts'],
  },
  {
    id: 'item-17',
    restaurantId: '1',
    name: 'Petit Gateau',
    description: 'Bolinho de chocolate com recheio cremoso que derrete na boca, acompanhado de sorvete de creme e frutas vermelhas.',
    ingredients: 'Chocolate meio amargo, farinha, ovos, manteiga, açúcar, sorvete de creme e frutas vermelhas',
    image: '🍰',
    categoryId: 'pb-sobremesas',
    prices: {
      mymenu: 18.90,
      ifood: 21.90,
      ubereats: 20.90,
      rappi: 21.50,
    },
    available: true,
    allergens: ['gluten', 'dairy', 'eggs'],
  },
  {
    id: 'item-18',
    restaurantId: '1',
    name: 'Sorvete Gourmet 500ml',
    description: 'Sorvete de excelente qualidade em vários sabores: chocolate, morango, maracujá e pistachio.',
    ingredients: 'Leite, creme de leite, açúcar, sabor escolhido',
    image: '🍦',
    categoryId: 'pb-sobremesas',
    prices: {
      mymenu: 12.90,
      ifood: 14.90,
      ubereats: 14.00,
      rappi: 14.50,
    },
    available: true,
    allergens: ['dairy'],
  },

  // PIZZARIA BELLA - ACOMPANHAMENTOS
  {
    id: 'item-19',
    restaurantId: '1',
    name: 'Batata Frita Premium',
    description: 'Batata frita crocante por fora e macia por dentro, temperada com sal grosso e alho. Perfeita para acompanhar.',
    ingredients: 'Batata, óleo vegetal, sal e alho',
    image: '🍟',
    categoryId: 'pb-acompanhamentos',
    prices: {
      mymenu: 8.90,
      ifood: 10.90,
      ubereats: 10.00,
      rappi: 10.50,
    },
    available: true,
    allergens: [],
  },
  {
    id: 'item-20',
    restaurantId: '1',
    name: 'Batata Cheddar e Bacon',
    description: 'Batata frita crocante coberta com molho cheddar cremoso e bacon crocante.',
    ingredients: 'Batata, óleo, sal, bacon, cheddar, maionese',
    image: '🍟',
    categoryId: 'pb-acompanhamentos',
    prices: {
      mymenu: 13.90,
      ifood: 16.90,
      ubereats: 16.00,
      rappi: 16.50,
    },
    available: true,
    allergens: ['dairy'],
  },
  {
    id: 'item-21',
    restaurantId: '1',
    name: 'Brotinhos de Alho',
    description: 'Seis brotinhos de pão caseiro levemente torrados e untados com manteiga de alho derretida. Irresistível!',
    ingredients: 'Pão caseiro, manteiga, alho, sal e parmesan',
    image: '🍞',
    categoryId: 'pb-acompanhamentos',
    prices: {
      mymenu: 7.90,
      ifood: 9.90,
      ubereats: 9.00,
      rappi: 9.50,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-22',
    restaurantId: '1',
    name: 'Asas de Frango ao Molho Barbecue',
    description: 'Asas de frango suculentas revestidas com nosso molho barbecue caseiro e queimado no forno.',
    ingredients: 'Asas de frango, molho barbecue, sal, pimenta',
    image: '🍗',
    categoryId: 'pb-acompanhamentos',
    prices: {
      mymenu: 16.90,
      ifood: 19.90,
      ubereats: 18.90,
      rappi: 19.50,
    },
    available: true,
    allergens: [],
  },

  // PRATOS BRASILEIROS
  {
    id: 'item-10',
    restaurantId: '6',
    name: 'Feijoada Completa',
    description: 'Autêntica feijoada com carne seca, linguiça e costela cozidas lentamente, acompanhada de farofa, couve salteada e arroz',
    ingredients: 'Feijão preto, carne seca, linguiça, costela, arroz, couve e farofa',
    image: '🍲',
    categoryId: 'cat-4',
    prices: {
      mymenu: 42.90,
      ifood: 47.90,
      ubereats: 45.90,
      rappi: 46.90,
    },
    available: true,
    allergens: ['gluten'],
  },
  {
    id: 'item-11',
    restaurantId: '6',
    name: 'Carne de Sol com Macaxeira',
    description: 'Carne de sol macia acompanhada de macaxeira frita crocante e salada verde fresca com molho caseiro',
    ingredients: 'Carne de sol, macaxeira, salada verde, tomate, cebola e molho caseiro',
    image: '🍖',
    categoryId: 'cat-4',
    prices: {
      mymenu: 38.90,
      ifood: 43.90,
      ubereats: 41.90,
    },
    available: true,
  },
  {
    id: 'item-12',
    restaurantId: '6',
    name: 'Parmegiana de Frango',
    description: 'Frango à milanesa coberto com molho de tomate caseiro, mussarela derretida e presunto, servido com batata frita',
    ingredients: 'Peito de frango, mussarela, presunto, molho de tomate, batata frita e temperos',
    image: '🍗',
    categoryId: 'cat-4',
    prices: {
      mymenu: 35.90,
      ifood: 39.90,
      ubereats: 37.90,
      rappi: 38.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-13',
    restaurantId: '6',
    name: 'Baião de Dois',
    description: 'Combinação tradicional de arroz com feijão verde, linguiça calabresa, queijo coalho fresco e carne seca',
    ingredients: 'Arroz, feijão verde, linguiça, queijo coalho, carne seca, cebola, alho e temperos',
    image: '🍚',
    categoryId: 'cat-4',
    prices: {
      mymenu: 28.90,
      ifood: 32.90,
      ubereats: 30.90,
    },
    available: true,
    allergens: ['dairy'],
  },

  // HAMBÚRGUERES E LANCHES
  {
    id: 'item-13a',
    restaurantId: '2',
    name: 'Hamburger Premium',
    description: 'Hambúrguer especial com carne suculenta, queijo derretido, bacon crocante e molho exclusivo da casa.',
    ingredients: 'Carne bovina premium, queijo, bacon, pão artesanal, alface, tomate e molho especial',
    image: '🍔',
    categoryId: 'bh-ofertas',
    prices: {
      mymenu: 35.90,
      ifood: 38.90,
      ubereats: 37.90,
      rappi: 38.50,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
    isOffer: true,
    offerPrice: 24.90,
  },
  {
    id: 'item-13b',
    restaurantId: '2',
    name: 'Fritas Premium',
    description: 'Batatas crocantes com tempero especial e maionese artesanal por tempo limitado.',
    ingredients: 'Batata, óleo, sal marinho, tempero especial e maionese artesanal',
    image: '🍟',
    categoryId: 'bh-ofertas',
    prices: {
      mymenu: 18.90,
      ifood: 20.90,
      ubereats: 19.90,
      rappi: 20.50,
    },
    available: true,
    isOffer: true,
    offerPrice: 12.90,
  },
  {
    id: 'item-14',
    restaurantId: '2',
    name: 'X-Burguer',
    description: 'Hambúrguer de carne bovina 150g com queijo fundido, alface, tomate, cebola roxa e nosso molho especial no pão de hambúrguer tostado',
    ingredients: 'Carne bovina, queijo, pão, alface, tomate, cebola, maionese especial e temperos',
    image: '🍔',
    categoryId: 'cat-5',
    prices: {
      mymenu: 18.90,
      ifood: 21.90,
      ubereats: 20.90,
      rappi: 20.50,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-15',
    restaurantId: '2',
    name: 'X-Bacon',
    description: 'Hambúrguer duplo 2x150g com bacon crocante, queijo meia cura, cebola caramelizada e nosso exclusivo molho barbecue',
    ingredients: 'Carne bovina, bacon, queijo, pão, cebola caramelizada, molho barbecue e temperos',
    image: '🥓',
    categoryId: 'cat-5',
    prices: {
      mymenu: 24.90,
      ifood: 27.90,
      ubereats: 26.90,
      rappi: 27.00,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-16',
    restaurantId: '2',
    name: 'Batata Frita Premium',
    description: 'Batata frita crocante preparada com batatas selecionadas, temperadas com sal marinho e ervas aromáticas',
    ingredients: 'Batata, óleo de canola, sal marinho, alho poró e temperos',
    image: '🍟',
    categoryId: 'cat-5',
    prices: {
      mymenu: 12.90,
      ifood: 14.90,
      ubereats: 13.90,
      rappi: 14.00,
    },
    available: true,
  },
  {
    id: 'item-17',
    restaurantId: '2',
    name: 'Combo Hambúrguer',
    description: 'X-Burguer, batata frita e refrigerante para uma refeição completa e satisfatória',
    ingredients: 'Hambúrguer completo, batata frita e refrigerante 1 litro',
    image: '🍔',
    categoryId: 'cat-5',
    prices: {
      mymenu: 38.90,
      ifood: 42.90,
      ubereats: 40.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },

  // SUSHI E TEMAKI
  {
    id: 'item-18',
    restaurantId: '3',
    name: 'Combo Sushi 20 peças',
    description: 'Seleção variada com 20 peças: california, philadelphia, temaki de salmão e hótéis selecionados pelo chef',
    ingredients: 'Arroz, nori, salmão, cream cheese, abacate, pepino e molhos especiais',
    image: '🍣',
    categoryId: 'cat-6',
    prices: {
      mymenu: 65.90,
      ifood: 73.90,
      ubereats: 69.90,
      rappi: 71.00,
    },
    available: true,
    allergens: ['gluten', 'shellfish'],
    isOffer: true,
    offerPrice: 59.90,
  },
  {
    id: 'item-19',
    restaurantId: '3',
    name: 'Hot Roll',
    description: 'Clássico irreverente: arroz, nori, salmão, cream cheese, abacate e maçã verde em fritas crocantes com molho especial',
    ingredients: 'Arroz temperado, nori, salmão fresco, cream cheese, abacate, maçã verde, panko e molho caseiro',
    image: '🍘',
    categoryId: 'cat-6',
    prices: {
      mymenu: 28.90,
      ifood: 32.90,
      ubereats: 30.90,
      rappi: 31.50,
    },
    available: true,
    allergens: ['gluten', 'dairy', 'shellfish'],
  },
  {
    id: 'item-20',
    restaurantId: '3',
    name: 'Temaki Salmão',
    description: 'Temaki em formato de cone com salmão fresco, abacate, pepino, maionese especial e gergelim',
    ingredients: 'Nori, arroz, salmão fresco, abacate, pepino, maionese, gergelim e temperos',
    image: '🍱',
    categoryId: 'cat-6',
    prices: {
      mymenu: 22.90,
      ifood: 25.90,
      ubereats: 24.90,
    },
    available: true,
    allergens: ['gluten', 'shellfish'],
  },
  {
    id: 'item-21',
    restaurantId: '3',
    name: 'Yakisoba',
    description: 'Macarrão crocante salteado com cenoura, repolho, frango desfiado e molho yakisoba especial finalizado com gergelim',
    ingredients: 'Macarrão yakisoba, frango, cenoura, repolho, molho yakisoba, gergelim e cebola roxa',
    image: '🍜',
    categoryId: 'cat-6',
    prices: {
      mymenu: 32.90,
      ifood: 36.90,
      ubereats: 34.90,
      rappi: 35.50,
    },
    available: true,
    allergens: ['gluten', 'shellfish'],
  },

  // DOCES E BOLOS
  {
    id: 'item-22',
    restaurantId: '8',
    name: 'Bolo de Pote',
    description: 'Delicioso bolo em camadas no potinho: massa fofa, chocolate, morango e calda doce - 300g',
    ingredients: 'Farinha de trigo, ovos, açúcar, chocolate, morango, calda doce e cobertura',
    image: '🍰',
    categoryId: 'cat-7',
    prices: {
      mymenu: 12.90,
      ifood: 14.90,
      ubereats: 13.90,
      rappi: 14.00,
    },
    available: true,
    allergens: ['gluten', 'dairy', 'eggs'],
    isOffer: true,
    offerPrice: 9.90,
  },
  {
    id: 'item-23',
    restaurantId: '8',
    name: 'Brigadeiro Gourmet',
    description: 'Brigadeiro artesanal feito com chocolate 70% qualidade premium, cobertura de granulado e embalagem especial',
    ingredients: 'Chocolate 70%, leite condensado, manteiga, granulado e papel ouro',
    image: '🍫',
    categoryId: 'cat-7',
    prices: {
      mymenu: 3.50,
      ifood: 4.50,
      ubereats: 4.00,
      rappi: 4.00,
    },
    available: true,
    allergens: ['dairy'],
  },
  {
    id: 'item-24',
    restaurantId: '8',
    name: 'Donut Recheado',
    description: 'Donut fofinho recheado com brigadeiro ou calda de chocolate e cobertura colorida de granulado - unidade',
    ingredients: 'Farinha, açúcar, ovos, leite, fermento, chocolate, cobertura e granulado',
    image: '🍩',
    categoryId: 'cat-7',
    prices: {
      mymenu: 8.90,
      ifood: 10.90,
      ubereats: 9.90,
      rappi: 10.00,
    },
    available: true,
    allergens: ['gluten', 'dairy', 'eggs'],
  },
  {
    id: 'item-25',
    restaurantId: '8',
    name: 'Brownie Artesanal',
    description: 'Brownie caseiro com chocolate belga derretido, nozes e calda de chocolate, servido levemente morno',
    ingredients: 'Chocolate belga, farinha, ovos, manteiga, açúcar, nozes e calda de chocolate',
    image: '🍫',
    categoryId: 'cat-7',
    prices: {
      mymenu: 14.90,
      ifood: 17.90,
      ubereats: 16.90,
      rappi: 17.00,
    },
    available: true,
    allergens: ['gluten', 'dairy', 'eggs', 'nuts'],
  },

  // BEBIDAS
  {
    id: 'item-26',
    restaurantId: '9a',
    name: 'Suco Natural Detox',
    description: 'Suco 100% natural feito na hora: maçã verde, gengibre, limão e folhas de hortelã para desintoxicação - 500ml',
    ingredients: 'Maçã verde, gengibre fresco, limão tahiti, hortelã e água filtrada',
    image: '🍏',
    categoryId: 'cat-2',
    prices: {
      mymenu: 12.90,
      ifood: 14.90,
      ubereats: 13.90,
      rappi: 14.00,
    },
    available: true,
    isOffer: true,
    offerPrice: 9.90,
  },
  {
    id: 'item-27',
    restaurantId: '9a',
    name: 'Milkshake Premium',
    description: 'Milkshake cremoso com gelado, leite integral, sorvete gourmet e xarope de qualidade - 400ml',
    ingredients: 'Leite integral, sorvete gourmet, xarope natural, gelo e calda de chocolate ou caramelo',
    image: '🥛',
    categoryId: 'cat-2',
    prices: {
      mymenu: 16.90,
      ifood: 19.90,
      ubereats: 18.90,
      rappi: 19.00,
    },
    available: true,
    allergens: ['dairy', 'nuts'],
  },
  {
    id: 'item-28',
    restaurantId: '9a',
    name: 'Café Gelado Especial',
    description: 'Café coado na hora, gelado com leite em pó integral, calda de caramelo caseira e espuma de canela - 300ml',
    image: '☕',
    categoryId: 'cat-2',
    prices: {
      mymenu: 11.90,
      ifood: 13.90,
      ubereats: 12.90,
      rappi: 13.00,
    },
    available: true,
    allergens: ['dairy'],
  },
  {
    id: 'item-29',
    restaurantId: '9a',
    name: 'Chopp Artesanal',
    description: 'Chopp gelado artesanal, selecionado especialmente para acompanhar sua refeição - 1 litro',
    image: '🍺',
    categoryId: 'cat-2',
    prices: {
      mymenu: 22.90,
      ifood: 25.90,
      ubereats: 24.90,
    },
    available: true,
  },

  // SALADAS E FIT - Salad Bar
  {
    id: 'item-30',
    restaurantId: '5',
    name: 'Salada Fit Completa',
    description: 'Mix de folhas verdes, alface roxa, tomate cereja, cenoura ralada, beterraba, ovos cozidos e molho vinagrete caseiro',
    ingredients: 'Alface, rúcula, tomate cereja, cenoura, beterraba, ovos, azeite de oliva e vinagre balsâmico',
    image: '🥗',
    categoryId: 'cat-8',
    prices: {
      mymenu: 24.90,
      ifood: 27.90,
      ubereats: 26.90,
      rappi: 27.00,
    },
    available: true,
    allergens: ['eggs'],
  },
  {
    id: 'item-31',
    restaurantId: '5',
    name: 'Frango Grelhado com Legumes',
    description: 'Peito de frango marinado e grelhado, acompanhado de brócolis, abóbora, cenoura cozida no vapor e arroz integral',
    ingredients: 'Peito de frango, brócolis, abóbora, cenoura, arroz integral, azeite e temperos naturais',
    image: '🍗',
    categoryId: 'cat-8',
    prices: {
      mymenu: 32.90,
      ifood: 36.90,
      ubereats: 34.90,
      rappi: 35.50,
    },
    available: true,
  },
  {
    id: 'item-32',
    restaurantId: '5',
    name: 'Wrap Natural',
    description: 'Tortilla integral recheada com frango desfiado, alface, tomate, cenoura ralada, azeite e molho light',
    ingredients: 'Tortilla integral, frango cozido, alface, tomate, cenoura, azeite de oliva e molho light',
    image: '🌯',
    categoryId: 'cat-8',
    prices: {
      mymenu: 20.90,
      ifood: 23.90,
      ubereats: 22.90,
      rappi: 23.00,
    },
    available: true,
    allergens: ['gluten'],
  },
  {
    id: 'item-33',
    restaurantId: '5',
    name: 'Bowl Proteico',
    description: 'Base de quinoa com frango marinado, abacate, ovos cozidos, nozes, cranberry e molho tahine caseiro',
    ingredients: 'Quinoa, frango, abacate, ovos, nozes, cranberry, tahine, limão e temperos',
    image: '🥙',
    categoryId: 'cat-8',
    prices: {
      mymenu: 28.90,
      ifood: 32.90,
      ubereats: 30.90,
      rappi: 31.50,
    },
    available: true,
    allergens: ['nuts'],
  },

  // SOBREMESAS - Pudim Casarão
  {
    id: 'item-34',
    restaurantId: '10a',
    name: 'Sorvete Artesanal',
    description: 'Sorvete caseiro cremoso com ingredientes 100% naturais. Sabores: chocolate belga, morango fresco ou doce de leite',
    ingredients: 'Leite integral, creme de leite, açúcar, chocolate belga, morango fresco ou doce de leite',
    image: '🍦',
    categoryId: 'cat-3',
    prices: {
      mymenu: 14.90,
      ifood: 17.90,
      ubereats: 16.90,
      rappi: 17.00,
    },
    available: true,
    allergens: ['dairy'],
  },
  {
    id: 'item-35',
    restaurantId: '10a',
    name: 'Pudim Casarão',
    description: 'Pudim caseiro cremoso preparado com leite condensado, calda de açúcar caramelizado, cobertura de calda e cereais',
    ingredients: 'Leite condensado, ovos, açúcar, leite, baunilha e cereais',
    image: '🍮',
    categoryId: 'cat-3',
    prices: {
      mymenu: 11.90,
      ifood: 13.90,
      ubereats: 12.90,
      rappi: 13.00,
    },
    available: true,
    allergens: ['dairy', 'eggs'],
  },
  {
    id: 'item-36',
    restaurantId: '10a',
    name: 'Açaí Especial',
    description: 'Base de açaí premium com granola crocante, mel natural, banana fresca, coco ralado e calda de leite condensado',
    ingredients: 'Açaí fresco, granola caseira, mel natural, banana, coco ralado e calda de leite condensado',
    image: '🫐',
    categoryId: 'cat-3',
    prices: {
      mymenu: 18.90,
      ifood: 21.90,
      ubereats: 20.90,
      rappi: 21.00,
    },
    available: true,
    allergens: ['dairy', 'nuts'],
  },
  {
    id: 'item-27',
    restaurantId: '9a',
    name: 'Milkshake Premium',
    description: 'Milkshake cremoso com gelado, leite integral, sorvete gourmet e xarope de qualidade - 400ml',
    ingredients: 'Leite integral, sorvete gourmet, xarope natural, gelo e calda de chocolate ou caramelo',
    image: '🥛',
    categoryId: 'cat-2',
    prices: {
      mymenu: 16.90,
      ifood: 19.90,
      ubereats: 18.90,
      rappi: 19.00,
    },
    available: true,
    allergens: ['dairy', 'nuts'],
  },
  {
    id: 'item-28',
    restaurantId: '9a',
    name: 'Café Gelado Especial',
    description: 'Café coado na hora, gelado com leite em pó integral, calda de caramelo caseira e espuma de canela - 300ml',
    image: '☕',
    categoryId: 'cat-2',
    prices: {
      mymenu: 11.90,
      ifood: 13.90,
      ubereats: 12.90,
      rappi: 13.00,
    },
    available: true,
    allergens: ['dairy'],
  },
  {
    id: 'item-29',
    restaurantId: '9a',
    name: 'Chopp Artesanal',
    description: 'Chopp gelado artesanal, selecionado especialmente para acompanhar sua refeição - 1 litro',
    image: '🍺',
    categoryId: 'cat-2',
    prices: {
      mymenu: 22.90,
      ifood: 25.90,
      ubereats: 24.90,
    },
    available: true,
  },

  // SALADAS E FIT
  {
    id: 'item-30',
    restaurantId: '5',
    name: 'Salada Fit Completa',
    description: 'Mix de folhas verdes, alface roxa, tomate cereja, cenoura ralada, beterraba, ovos cozidos e molho vinagrete caseiro',
    ingredients: 'Alface, rúcula, tomate cereja, cenoura, beterraba, ovos, azeite de oliva e vinagre balsâmico',
    image: '🥗',
    categoryId: 'cat-8',
    prices: {
      mymenu: 24.90,
      ifood: 27.90,
      ubereats: 26.90,
      rappi: 27.00,
    },
    available: true,
    allergens: ['eggs'],
  },
  {
    id: 'item-31',
    restaurantId: '5',
    name: 'Frango Grelhado com Legumes',
    description: 'Peito de frango marinado e grelhado, acompanhado de brócolis, abóbora, cenoura cozida no vapor e arroz integral',
    ingredients: 'Peito de frango, brócolis, abóbora, cenoura, arroz integral, azeite e temperos naturais',
    image: '🍗',
    categoryId: 'cat-8',
    prices: {
      mymenu: 32.90,
      ifood: 36.90,
      ubereats: 34.90,
      rappi: 35.50,
    },
    available: true,
  },
  {
    id: 'item-32',
    restaurantId: '5',
    name: 'Wrap Natural',
    description: 'Tortilla integral recheada com frango desfiado, alface, tomate, cenoura ralada, azeite e molho light',
    ingredients: 'Tortilla integral, frango cozido, alface, tomate, cenoura, azeite de oliva e molho light',
    image: '🌯',
    categoryId: 'cat-8',
    prices: {
      mymenu: 20.90,
      ifood: 23.90,
      ubereats: 22.90,
      rappi: 23.00,
    },
    available: true,
    allergens: ['gluten'],
  },
  {
    id: 'item-33',
    restaurantId: '5',
    name: 'Bowl Proteico',
    description: 'Base de quinoa com frango marinado, abacate, ovos cozidos, nozes, cranberry e molho tahine caseiro',
    ingredients: 'Quinoa, frango, abacate, ovos, nozes, cranberry, tahine, limão e temperos',
    image: '🥙',
    categoryId: 'cat-8',
    prices: {
      mymenu: 28.90,
      ifood: 32.90,
      ubereats: 30.90,
      rappi: 31.50,
    },
    available: true,
    allergens: ['nuts'],
  },

  // SOBREMESAS
  {
    id: 'item-34',
    restaurantId: '10a',
    name: 'Sorvete Artesanal',
    description: 'Sorvete caseiro cremoso com ingredientes 100% naturais. Sabores: chocolate belga, morango fresco ou doce de leite',
    ingredients: 'Leite integral, creme de leite, açúcar, chocolate belga, morango fresco ou doce de leite',
    image: '🍦',
    categoryId: 'cat-3',
    prices: {
      mymenu: 14.90,
      ifood: 17.90,
      ubereats: 16.90,
      rappi: 17.00,
    },
    available: true,
    allergens: ['dairy'],
  },
  {
    id: 'item-35',
    restaurantId: '10a',
    name: 'Pudim Casarão',
    description: 'Pudim caseiro cremoso preparado com leite condensado, calda de açúcar caramelizado, cobertura de calda e cereais',
    ingredients: 'Leite condensado, ovos, açúcar, leite, baunilha e cereais',
    image: '🍮',
    categoryId: 'cat-3',
    prices: {
      mymenu: 11.90,
      ifood: 13.90,
      ubereats: 12.90,
      rappi: 13.00,
    },
    available: true,
    allergens: ['dairy', 'eggs'],
  },
  {
    id: 'item-36',
    restaurantId: '10a',
    name: 'Açaí Especial',
    description: 'Base de açaí premium com granola crocante, mel natural, banana fresca, coco ralado e calda de leite condensado',
    ingredients: 'Açaí fresco, granola caseira, mel natural, banana, coco ralado e calda de leite condensado',
    image: '🫐',
    categoryId: 'cat-3',
    prices: {
      mymenu: 18.90,
      ifood: 21.90,
      ubereats: 20.90,
      rappi: 21.00,
    },
    available: true,
    allergens: ['dairy', 'nuts'],
  },
  // PIZZARIA MILANO - Restaurante 1a
  {
    id: 'item-37',
    restaurantId: '1a',
    name: 'Pizza Quattro Formaggi',
    description: 'Combinação deliciosa de quatro queijos premium: gorgonzola, brie, parmesão e mussarela com toque de mel',
    ingredients: 'Gorgonzola, brie, parmesão, mussarela, mel e azeite',
    image: '🍕',
    categoryId: 'cat-1',
    prices: {
      mymenu: 42.90,
      ifood: 46.90,
      ubereats: 45.00,
      rappi: 45.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-38',
    restaurantId: '1a',
    name: 'Pizza Frango com Requeijão',
    description: 'Peito de frango desfiado com requeijão cremoso, milho e cebola em massa crocante',
    ingredients: 'Molho de tomate, mussarela, frango desfiado, requeijão, milho e cebola',
    image: '🍕',
    categoryId: 'cat-1',
    prices: {
      mymenu: 36.90,
      ifood: 40.90,
      ubereats: 38.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-39',
    restaurantId: '1a',
    name: 'Pizza Vegetariana',
    description: 'Seleção especial de vegetais: brócolis, pimentão, cogumelo, tomate seco e azeitona preta',
    ingredients: 'Molho de tomate, mussarela, brócolis, pimentão, cogumelo, tomate seco e azeitona',
    image: '🍕',
    categoryId: 'cat-1',
    prices: {
      mymenu: 35.90,
      ifood: 39.90,
      ubereats: 37.90,
      rappi: 38.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-40',
    restaurantId: '1a',
    name: 'Refrigerante 2L',
    description: 'Bebida gelada - Coca-Cola, Guaraná Antarctica ou Fanta',
    ingredients: 'Refrigerante 2 litros',
    image: '🥤',
    categoryId: 'cat-2',
    prices: {
      mymenu: 10.00,
      ifood: 12.00,
      ubereats: 11.00,
    },
    available: true,
  },
  {
    id: 'item-41',
    restaurantId: '1a',
    name: 'Sorvete Gourmet',
    description: 'Sorvete artesanal em diversos sabores: chocolate, morango, baunilha e pistachio',
    ingredients: 'Leite, creme, açúcar e saborizantes naturais',
    image: '🍦',
    categoryId: 'cat-3',
    prices: {
      mymenu: 12.90,
      ifood: 14.90,
      ubereats: 13.90,
    },
    available: true,
    allergens: ['dairy'],
  },
  // PIZZA SUPREMA - Restaurante 1b
  {
    id: 'item-42',
    restaurantId: '1b',
    name: 'Pizza Suprema Premium',
    description: 'Nossa especialidade com calabresa, presunto, frango, bacon, cebola e pimentão em massa extra grossa',
    ingredients: 'Molho especial, mussarela, calabresa, presunto, frango, bacon, cebola e pimentão',
    image: '🍕',
    categoryId: 'cat-1',
    prices: {
      mymenu: 45.90,
      ifood: 49.90,
      ubereats: 47.90,
      rappi: 48.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-43',
    restaurantId: '1b',
    name: 'Pizza Havaiiana',
    description: 'Presunto, abacaxi fresco e mussarela em harmonia perfeita',
    ingredients: 'Molho de tomate, mussarela, presunto e abacaxi',
    image: '🍕',
    categoryId: 'cat-1',
    prices: {
      mymenu: 38.90,
      ifood: 42.90,
      ubereats: 40.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-44',
    restaurantId: '1b',
    name: 'Pizza Rúcula e Parmesão',
    description: 'Base de mussarela com tomate seco, rúcula fresca e parmesão ralado na hora',
    ingredients: 'Molho de tomate, mussarela, tomate seco, rúcula e parmesão',
    image: '🍕',
    categoryId: 'cat-1',
    prices: {
      mymenu: 40.90,
      ifood: 44.90,
      ubereats: 42.90,
      rappi: 43.90,
    },
    exclusive: 'presencial',
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-45',
    restaurantId: '1b',
    name: 'Suco de Laranja Natural',
    description: 'Suco fresco feito na hora com laranjas selecionadas',
    ingredients: 'Laranja fresca',
    image: '🧃',
    categoryId: 'cat-2',
    prices: {
      mymenu: 8.00,
      ifood: 9.50,
      ubereats: 9.00,
    },
    available: true,
  },
  {
    id: 'item-46',
    restaurantId: '1b',
    name: 'Pudim de Leite Condensado',
    description: 'Pudim cremoso e delicado coberto com calda de caramelo caseira',
    ingredients: 'Leite condensado, leite, ovos, açúcar e calda de caramelo',
    image: '🍮',
    categoryId: 'cat-3',
    prices: {
      mymenu: 14.90,
      ifood: 16.90,
      ubereats: 15.90,
    },
    available: true,
    allergens: ['dairy', 'eggs'],
  },
  // PIZZARIA DA VOVÓ - Restaurante 1c
  {
    id: 'item-47',
    restaurantId: '1c',
    name: 'Pizza Frango com Catupiry',
    description: 'Frango desfiado com catupiry cremoso e cebola em massa tradicional da vovó',
    ingredients: 'Molho de tomate, mussarela, frango desfiado, catupiry e cebola',
    image: '🍕',
    categoryId: 'cat-1',
    prices: {
      mymenu: 37.90,
      ifood: 41.90,
      ubereats: 39.90,
      rappi: 40.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-48',
    restaurantId: '1c',
    name: 'Pizza Brigadeiro com Leite Condensado',
    description: 'Doce irresistível com brigadeiro artesanal e leite condensado para os amantes de sabores intensos',
    ingredients: 'Massa doce da vovó, brigadeiro, leite condensado e crocante de chocolate',
    image: '🍕',
    categoryId: 'cat-1',
    prices: {
      mymenu: 32.90,
      ifood: 36.90,
      ubereats: 34.90,
    },
    exclusive: 'presencial',
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-49',
    restaurantId: '1c',
    name: 'Pizza de Banana com Canela',
    description: 'Massa crocante com banana fresca, canela e açúcar cristal - receita secreta da vovó',
    ingredients: 'Massa da vovó, banana, canela, açúcar cristal e manteiga',
    image: '🍕',
    categoryId: 'cat-1',
    prices: {
      mymenu: 33.90,
      ifood: 37.90,
      ubereats: 35.90,
      rappi: 36.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-50',
    restaurantId: '1c',
    name: 'Suco da Vovó (Abacaxi com Gengibre)',
    description: 'Suco refrescante com abacaxi fresco e gengibre - receita tradicional da família',
    ingredients: 'Abacaxi fresco, gengibre fresco e água',
    image: '🧃',
    categoryId: 'cat-2',
    prices: {
      mymenu: 9.00,
      ifood: 10.50,
      ubereats: 10.00,
    },
    available: true,
  },
  {
    id: 'item-51',
    restaurantId: '1c',
    name: 'Pavê de Maizena da Vovó',
    description: 'Sobremesa clássica feita a mão com maizena, leite condensado e cobertura de chocolate - segredo guardado há gerações',
    ingredients: 'Maizena, leite, leite condensado, ovos, açúcar e chocolate',
    image: '🍰',
    categoryId: 'cat-3',
    prices: {
      mymenu: 13.90,
      ifood: 15.90,
      ubereats: 14.90,
    },
    available: true,
    allergens: ['dairy', 'eggs'],
  },
];
