import type { Restaurant } from '../types/restaurant';

export const mockRestaurants: Restaurant[] = [
  // PIZZA
  {
    id: '1',
    slug: 'pizzaria-bella',
    name: 'Pizzaria Bella',
    logo: '🍕',
    plan: 'diamante',
    rating: 4.8,
    category: 'Pizza',
    distance: 1.2,
    isOpen: true,
    deliveryTime: '30-40 min',
    minOrder: 25,
    headerColor: '#C92924',
  },
  {
    id: '1a',
    slug: 'pizzaria-milano',
    name: 'Pizzaria Milano',
    logo: '🍕',
    plan: 'ouro',
    rating: 4.7,
    category: 'Pizza',
    distance: 2.1,
    isOpen: true,
    deliveryTime: '35-45 min',
    minOrder: 28,
  },
  {
    id: '1b',
    slug: 'pizza-suprema',
    name: 'Pizza Suprema',
    logo: '🍕',
    plan: 'diamante',
    rating: 4.9,
    category: 'Pizza',
    distance: 0.9,
    isOpen: true,
    deliveryTime: '25-35 min',
    minOrder: 22,
  },
  {
    id: '1c',
    slug: 'pizzaria-vovo',
    name: 'Pizzaria da Vovó',
    logo: '🍕',
    plan: 'prata',
    rating: 4.5,
    category: 'Pizza',
    distance: 3.0,
    isOpen: true,
    deliveryTime: '40-50 min',
    minOrder: 30,
  },

  // HAMBURGUERIA / LANCHES
  {
    id: '2',
    slug: 'burger-house',
    name: 'Burger House',
    logo: '🍔',
    plan: 'ouro',
    rating: 4.6,
    category: 'Lanches',
    distance: 0.8,
    isOpen: true,
    deliveryTime: '25-35 min',
    minOrder: 20,
  },
  {
    id: '2a',
    slug: 'hamburgueria-artesanal',
    name: 'Hamburgueria Artesanal',
    logo: '🍔',
    plan: 'diamante',
    rating: 4.8,
    category: 'Lanches',
    distance: 1.5,
    isOpen: true,
    deliveryTime: '30-40 min',
    minOrder: 25,
  },
  {
    id: '2b',
    slug: 'fast-burger',
    name: 'Fast Burger',
    logo: '🍔',
    plan: 'ouro',
    rating: 4.4,
    category: 'Lanches',
    distance: 0.6,
    isOpen: true,
    deliveryTime: '20-30 min',
    minOrder: 18,
  },
  {
    id: '2c',
    slug: 'smash-burger',
    name: 'Smash Burger Bar',
    logo: '🍔',
    plan: 'prata',
    rating: 4.7,
    category: 'Lanches',
    distance: 2.2,
    isOpen: true,
    deliveryTime: '35-45 min',
    minOrder: 24,
  },

  // JAPONESA
  {
    id: '3',
    slug: 'sushi-zen',
    name: 'Sushi Zen',
    logo: '🍣',
    plan: 'diamante',
    rating: 4.9,
    category: 'Japonesa',
    distance: 2.5,
    isOpen: true,
    deliveryTime: '40-50 min',
    minOrder: 35,
  },
  {
    id: '3a',
    slug: 'temakeria-tokyo',
    name: 'Temakeria Tokyo',
    logo: '🍱',
    plan: 'ouro',
    rating: 4.8,
    category: 'Japonesa',
    distance: 1.5,
    isOpen: true,
    deliveryTime: '30-40 min',
    minOrder: 30,
  },
  {
    id: '3b',
    slug: 'ramen-house',
    name: 'Ramen House',
    logo: '🍜',
    plan: 'ouro',
    rating: 4.6,
    category: 'Japonesa',
    distance: 1.8,
    isOpen: true,
    deliveryTime: '35-45 min',
    minOrder: 28,
  },
  {
    id: '3c',
    slug: 'yakitori-master',
    name: 'Yakitori Master',
    logo: '🍢',
    plan: 'prata',
    rating: 4.5,
    category: 'Japonesa',
    distance: 2.8,
    isOpen: true,
    deliveryTime: '45-55 min',
    minOrder: 32,
  },

  // BRASILEIRA
  {
    id: '6',
    slug: 'churrascaria-gaucha',
    name: 'Churrascaria Gaúcha',
    logo: '🥩',
    plan: 'prata',
    rating: 4.4,
    category: 'Brasileira',
    distance: 3.2,
    isOpen: true,
    deliveryTime: '45-55 min',
    minOrder: 40,
  },
  {
    id: '6a',
    slug: 'restaurante-feijoada',
    name: 'Feijoada & Cia',
    logo: '🍲',
    plan: 'ouro',
    rating: 4.7,
    category: 'Brasileira',
    distance: 2.0,
    isOpen: true,
    deliveryTime: '40-50 min',
    minOrder: 32,
  },
  {
    id: '6b',
    slug: 'boteco-do-bairro',
    name: 'Boteco do Bairro',
    logo: '🍗',
    plan: 'prata',
    rating: 4.5,
    category: 'Brasileira',
    distance: 1.2,
    isOpen: true,
    deliveryTime: '30-40 min',
    minOrder: 25,
  },
  {
    id: '6c',
    slug: 'moqueca-bahiana',
    name: 'Moqueca Bahiana',
    logo: '🥘',
    plan: 'diamante',
    rating: 4.8,
    category: 'Brasileira',
    distance: 2.5,
    isOpen: true,
    deliveryTime: '35-45 min',
    minOrder: 30,
  },

  // DOCES
  {
    id: '8',
    slug: 'acai-tropical',
    name: 'Açaí Tropical',
    logo: '🍨',
    plan: 'basico',
    rating: 4.6,
    category: 'Doces',
    distance: 0.5,
    isOpen: true,
    deliveryTime: '15-25 min',
    minOrder: 15,
  },
  {
    id: '8a',
    slug: 'confeitaria-sonho',
    name: 'Confeitaria Sonho',
    logo: '🧁',
    plan: 'ouro',
    rating: 4.8,
    category: 'Doces',
    distance: 0.8,
    isOpen: true,
    deliveryTime: '20-30 min',
    minOrder: 18,
  },
  {
    id: '8b',
    slug: 'sorvete-gourmet',
    name: 'Sorvete Gourmet',
    logo: '🍦',
    plan: 'prata',
    rating: 4.7,
    category: 'Doces',
    distance: 1.0,
    isOpen: true,
    deliveryTime: '15-25 min',
    minOrder: 16,
  },
  {
    id: '8c',
    slug: 'brigaderia-artesanal',
    name: 'Brigaderia Artesanal',
    logo: '🍫',
    plan: 'diamante',
    rating: 4.9,
    category: 'Doces',
    distance: 0.7,
    isOpen: true,
    deliveryTime: '20-30 min',
    minOrder: 17,
  },

  // BEBIDAS
  {
    id: '9a',
    slug: 'juice-bar',
    name: 'Juice Bar Premium',
    logo: '🥤',
    plan: 'ouro',
    rating: 4.6,
    category: 'Bebidas',
    distance: 0.9,
    isOpen: true,
    deliveryTime: '10-20 min',
    minOrder: 12,
  },
  {
    id: '9b',
    slug: 'cafeteria-aroma',
    name: 'Cafeteria Aroma',
    logo: '☕',
    plan: 'ouro',
    rating: 4.7,
    category: 'Bebidas',
    distance: 1.1,
    isOpen: true,
    deliveryTime: '15-25 min',
    minOrder: 14,
  },
  {
    id: '9c',
    slug: 'smoothie-paradise',
    name: 'Smoothie Paradise',
    logo: '🥤',
    plan: 'prata',
    rating: 4.5,
    category: 'Bebidas',
    distance: 1.3,
    isOpen: true,
    deliveryTime: '10-20 min',
    minOrder: 13,
  },
  {
    id: '9d',
    slug: 'cha-oriental',
    name: 'Chá Oriental',
    logo: '🍵',
    plan: 'basico',
    rating: 4.4,
    category: 'Bebidas',
    distance: 1.5,
    isOpen: true,
    deliveryTime: '15-25 min',
    minOrder: 11,
  },

  // SAUDÁVEL
  {
    id: '5',
    slug: 'salad-bar',
    name: 'Salad Bar',
    logo: '🥗',
    plan: 'ouro',
    rating: 4.7,
    category: 'Saudável',
    distance: 1.0,
    isOpen: true,
    deliveryTime: '20-30 min',
    minOrder: 18,
  },
  {
    id: '5a',
    slug: 'bowl-fit',
    name: 'Bowl Fit',
    logo: '🥙',
    plan: 'ouro',
    rating: 4.8,
    category: 'Saudável',
    distance: 0.7,
    isOpen: true,
    deliveryTime: '15-25 min',
    minOrder: 16,
  },
  {
    id: '5b',
    slug: 'granola-natural',
    name: 'Granola Natural',
    logo: '🥗',
    plan: 'prata',
    rating: 4.6,
    category: 'Saudável',
    distance: 1.2,
    isOpen: true,
    deliveryTime: '20-30 min',
    minOrder: 17,
  },
  {
    id: '5c',
    slug: 'detox-juice',
    name: 'Detox Juice',
    logo: '🥬',
    plan: 'ouro',
    rating: 4.7,
    category: 'Saudável',
    distance: 0.9,
    isOpen: true,
    deliveryTime: '15-25 min',
    minOrder: 15,
  },

  // SOBREMESAS
  {
    id: '10a',
    slug: 'pudim-casarão',
    name: 'Pudim Casarão',
    logo: '🍮',
    plan: 'basico',
    rating: 4.5,
    category: 'Sobremesas',
    distance: 0.6,
    isOpen: true,
    deliveryTime: '15-25 min',
    minOrder: 14,
  },
  {
    id: '10b',
    slug: 'mousse-divino',
    name: 'Mousse Divino',
    logo: '🍰',
    plan: 'ouro',
    rating: 4.8,
    category: 'Sobremesas',
    distance: 0.8,
    isOpen: true,
    deliveryTime: '15-25 min',
    minOrder: 16,
  },
  {
    id: '10c',
    slug: 'cheesecake-premium',
    name: 'Cheesecake Premium',
    logo: '🍰',
    plan: 'diamante',
    rating: 4.9,
    category: 'Sobremesas',
    distance: 1.2,
    isOpen: true,
    deliveryTime: '20-30 min',
    minOrder: 18,
  },
  {
    id: '10d',
    slug: 'brownie-gourmet',
    name: 'Brownie Gourmet',
    logo: '🍫',
    plan: 'prata',
    rating: 4.6,
    category: 'Sobremesas',
    distance: 0.9,
    isOpen: true,
    deliveryTime: '15-25 min',
    minOrder: 15,
  },

  // ITALIANAS
  {
    id: '7',
    slug: 'pasta-fresca',
    name: 'Pasta Fresca',
    logo: '🍝',
    plan: 'basico',
    rating: 4.3,
    category: 'Italiana',
    distance: 2.0,
    isOpen: true,
    deliveryTime: '35-45 min',
    minOrder: 28,
  },

  // PADARIA
  {
    id: '11',
    slug: 'padaria-do-bairro',
    name: 'Padaria do Bairro',
    logo: '🥖',
    plan: 'basico',
    rating: 4.2,
    category: 'Padaria',
    distance: 0.3,
    isOpen: true,
    deliveryTime: '10-20 min',
    minOrder: 10,
  },
];
