import type { MenuCategory, MenuItem } from '../types/restaurant';

export const mockCategories: MenuCategory[] = [
  { id: 'cat-1', name: 'Pizzas', order: 1 },
  { id: 'cat-2', name: 'Bebidas', order: 2 },
  { id: 'cat-3', name: 'Sobremesas', order: 3 },
];

export const mockMenuItems: MenuItem[] = [
  {
    id: 'item-1',
    name: 'Pizza Margherita',
    description: 'A combinação atemporal de molho de tomate pelati, muçarela derretida e folhas frescas de manjericão, finalizada com um fio de azeite de oliva extra virgem.',
    ingredients: 'Molho de tomate, mussarela, manjericão e azeite',
    image: '🍕',
    categoryId: 'cat-1',
    prices: {
      mymenu: 35.90,
      ifood: 39.90,
      ubereats: 37.90,
      rappi: 38.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-2',
    name: 'Pizza Calabresa',
    description: 'Sabor marcante da calabresa artesanal com cebola roxa caramelizada sobre generosa camada de mussarela.',
    ingredients: 'Molho de tomate, mussarela, calabresa e cebola',
    image: '🍕',
    categoryId: 'cat-1',
    prices: {
      mymenu: 38.90,
      ifood: 42.90,
      ubereats: 40.90,
    },
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-3',
    name: 'Pizza Portuguesa',
    description: 'Uma explosão de sabores com presunto, ovos, cebola e azeitonas pretas sobre nossa massa artesanal.',
    ingredients: 'Molho de tomate, mussarela, presunto, ovos, cebola e azeitonas',
    image: '🍕',
    categoryId: 'cat-1',
    prices: {
      ifood: 45.90,
      ubereats: 43.90,
      rappi: 44.90,
    },
    exclusive: 'delivery',
    available: true,
    allergens: ['gluten', 'dairy', 'eggs'],
  },
  {
    id: 'item-4',
    name: 'Pizza Especial da Casa',
    description: 'Nossa criação exclusiva que combina ingredientes premium selecionados pelo chef. Uma experiência gastronômica única que só você encontra aqui.',
    ingredients: 'Molho especial da casa, mussarela de búfala, tomate seco, rúcula, parmesão e azeite trufado',
    image: '🍕',
    categoryId: 'cat-1',
    prices: {
      mymenu: 48.90,
    },
    exclusive: 'presencial',
    available: true,
    allergens: ['gluten', 'dairy'],
  },
  {
    id: 'item-5',
    name: 'Refrigerante 2L',
    description: 'Bebida gelada perfeita para acompanhar sua refeição. Escolha entre Coca-Cola, Guaraná Antarctica ou Fanta Laranja.',
    ingredients: 'Refrigerante 2 litros - Coca-Cola, Guaraná ou Fanta',
    image: '🥤',
    categoryId: 'cat-2',
    prices: {
      mymenu: 10.00,
      ifood: 12.00,
      ubereats: 11.00,
      rappi: 11.50,
    },
    available: true,
  },
  {
    id: 'item-6',
    name: 'Suco Natural 500ml',
    description: 'Suco 100% natural feito na hora com frutas frescas selecionadas. Opções: laranja, limão ou morango.',
    ingredients: 'Frutas frescas (laranja, limão ou morango) e água',
    image: '🧃',
    categoryId: 'cat-2',
    prices: {
      mymenu: 8.00,
      ifood: 9.50,
      ubereats: 9.00,
    },
    available: true,
  },
  {
    id: 'item-7',
    name: 'Água Mineral',
    description: 'Água mineral pura e refrescante. Disponível com ou sem gás, sempre gelada.',
    ingredients: 'Água mineral 500ml',
    image: '💧',
    categoryId: 'cat-2',
    prices: {
      mymenu: 4.00,
      ifood: 5.00,
      ubereats: 4.50,
      rappi: 4.50,
    },
    available: true,
  },
  {
    id: 'item-8',
    name: 'Brownie de Chocolate',
    description: 'Brownie artesanal de chocolate belga, crocante por fora e cremoso por dentro, servido quente com sorvete de creme e calda de chocolate.',
    ingredients: 'Chocolate belga, farinha, ovos, manteiga, açúcar, nozes e sorvete de creme',
    image: '🍫',
    categoryId: 'cat-3',
    prices: {
      mymenu: 15.90,
      ifood: 17.90,
      ubereats: 16.90,
      rappi: 17.50,
    },
    available: true,
    allergens: ['gluten', 'dairy', 'eggs', 'nuts'],
  },
  {
    id: 'item-9',
    name: 'Petit Gateau',
    description: 'Bolinho de chocolate com recheio cremoso que derrete na boca, acompanhado de sorvete de creme e frutas vermelhas.',
    ingredients: 'Chocolate meio amargo, farinha, ovos, manteiga, açúcar, sorvete de creme e frutas vermelhas',
    image: '🍰',
    categoryId: 'cat-3',
    prices: {
      mymenu: 18.90,
      ifood: 21.90,
      ubereats: 20.90,
    },
    available: false,
    allergens: ['gluten', 'dairy', 'eggs'],
  },
];
